### ISSUE TITLE
Game does not run with pygame 2.1.2: AttributeError: 'Event' object has no attribute 'gain'

### ISSUE THREAD

**Issue by jwhitham** [20kly/20kly#4]
Environment - Python 3.10.0, pygame 2.1.2, running from source code on Windows

The game crashes:
```
Traceback (most recent call last):
  File "c:\temp\20kly\lightyears", line 80, in <module>
    sys.exit(Main(data_dir=data_dir, args=sys.argv[1:], event=Events()))
  File "c:\temp\20kly\lib20k\main.py", line 124, in Main
    quit = Main_Menu_Loop(TITLE, clock, event)
  File "c:\temp\20kly\lib20k\main.py", line 203, in Main_Menu_Loop
    (quit, cmd) = menu.Simple_Menu_Loop(screen, current_menu,
  File "c:\temp\20kly\lib20k\menu.py", line 284, in Simple_Menu_Loop
    e = event.poll()
  File "c:\temp\20kly\lib20k\events.py", line 56, in poll
    return Event(pygame.event.poll(), self)
  File "c:\temp\20kly\lib20k\events.py", line 43, in __init__
    self.gain = base.gain
AttributeError: 'Event' object has no attribute 'gain'
```

Looks like this is a pygame bug: https://stackoverflow.com/questions/73273424/cant-access-event-state-or-event-gain-of-activeevent

**Comment by jwhitham** [comment]
Added workaround in commit 72bb7a039eb66add3816072602ce0581960bb69e
